export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const FETCH_UNI_BEGIN = 'FETCH_UNI_BEGIN';
export const FETCH_UNI_SUCCESS = 'FETCH_UNI_SUCCESS';
export const FETCH_UNI_FAILURE = 'FETCH_UNI_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';